version: "3"
services:
  sftp-server:
    image: groundspace/simple-sftp-server:latest
    build: .
    container_name: sftp-server
    ports:
      - "2222:22"
    volumes:
      - ./data:/home/user
